### ISSUE TITLE
ADM-CID: Last line could not be parsed as a SIAEvent or OHEvent

### ISSUE THREAD

**Issue by bropat** [eavanvalkenburg/pysiaalarm#22]
System informations:

```
System Health

version: core-2021.9.7
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.62
arch: x86_64
timezone: Europe/Rome

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 6.4
update_channel: stable
supervisor_version: supervisor-2021.09.6
docker_version: 20.10.7
disk_total: 30.8 GB
disk_used: 2.0 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.3.3)

dashboards: 1
resources: 0
views: 1
mode: storage
```

I get the following error message:

```
DEBUG (MainThread) [pysiaalarm.aio.client] Starting SIA.
DEBUG (MainThread) [pysiaalarm.base_server] Incoming line: D0850078"*ADM-CID"6879R0L0#123F[64F7ADD9BA9377DBF2C014BC709329BEEE345B5F20C60B7EB9D2C6B8C222666B13D0B4A114B448B0AC555FCC658DB6EE
WARNING (MainThread) [pysiaalarm.base_server] Last line could not be parsed as a SIAEvent or OHEvent, line was: D0850078"*ADM-CID"6879R0L0#123F[64F7ADD9BA9377DBF2C014BC709329BEEE345B5F20C60B7EB9D2C6B8C222666B13D0B4A114B448B0AC555FCC658DB6EE
```

Can you maybe help me?

Thanks!

Regards
Patrick

**Comment by eavanvalkenburg** [comment]
Could you turn on some additional logging and post here:
```
logger:
  default: error
  logs:
    homeassistant.components.sia: debug 
    pysiaalarm: debug
```

**Comment by bropat** [comment]
This configuration is already active. No more log than above is generated.

**Comment by eavanvalkenburg** [comment]
ok and this is using the official integration or the HACS one?

**Comment by bropat** [comment]
Official

**Comment by eavanvalkenburg** [comment]
ok, so I added the line above to the tests and there it works so there is something else going on, you have the keys used for encrypting the same in both? and could you do a test without encryption?

**Comment by bropat** [comment]
> ok, so I added the line above to the tests and there it works so there is something else going on, you have the keys used for encrypting the same in both?

Yes i have. I already have a working integration with another home automation solution ([ioBroker](https://www.iobroker.net/#en/intro) with [ioBroker.sia](https://github.com/schmupu/ioBroker.sia)). 

> and could you do a test without encryption?

No, I'm afraid I can't.

When looking at the code, the cause can actually only be [here]( https://github.com/eavanvalkenburg/pysiaalarm/blob/f79fa061a955dda35221a4cd85916392c566b580/src/pysiaalarm/event.py#L138-L139), as the following log line can only be thrown by an `EventFormatError` exception:

```
WARNING (MainThread) [pysiaalarm. base_server] Last line could not be parsed as a SIAEvent or OHEvent, line was: D0850078"*ADM-CID "6879R0L0#123F[64F7ADD9BA9377DBF2C014BC709329BEEE345B5F20C60B7EB9D2C6B8C222666B13D0B4A114B448B0AC555FCC658DB6EE
```

The regular expression is also correct according to me....

**Comment by eavanvalkenburg** [comment]
No that is not completely the case, it can also be raised by the parse_content function later on [(here)](https://github.com/eavanvalkenburg/pysiaalarm/blob/f79fa061a955dda35221a4cd85916392c566b580/src/pysiaalarm/event.py#L373). So I noticed there is a small gap when the account is not encrypted but the message is, which would result in trying to parse content in the wrong way which throws the eventformaterror as well. So I'm doing two things now that will hopefully help with this one. 1) check if both the message and the account are encrypted 2) change the logged error for the other situation.

**Comment by bropat** [comment]
You're right, I overlooked it :P
Sounds good.

Thanks!

**Comment by bropat** [comment]
> I am! In my alarm they ask you to set the key as a hex, so you type in a key with just 0-9A-F, but I'll have a look!

@eavanvalkenburg 

Have you looked?

**Comment by eavanvalkenburg** [comment]
@bropat could you share an example of the key you use, especially the format?

**Comment by bropat** [comment]
@eavanvalkenburg 

For example: `4474415a4458714f6961674662736a36`

**Comment by bropat** [comment]
> Well, I think changing that would break other alarms. Most alarms use a key inputted as string with just hex characters, so I will have to test to see. What is the key you use?

Another proposal in contrast to [this](
https://github.com/eavanvalkenburg/pysiaalarm/issues/22#issuecomment-951073239) is:

If you accept any string as a key and do not check whether it is a HEX "string", i.e. only check the length of the string in bytes, it also works for me.

---

My key is a string that has been converted to a hex key so that it can be entered into the alarm system as a numeric hex key (not as a hex string). Unfortunately, I cannot change this key without contacting the alarm company.

Example:

Original Key as string: dhF3978fbas5Naj1
Hex Key (numeric!) used in the alarm system: 6468463339373866626173354e616a31

When I enter the string in the SIA integration, I get the error that it is not a "hex string", but would be correctly translated by pysiaalarm into a byte array and it would work.
If I enter the HEX value of the string, it does not work, of course, because the corresponding byte array does not correspond to the stored keys in the alarm system (numeric hex values).

I hope I have expressed myself better ;)
