### ISSUE TITLE
IPC-A42-B and IPC-S42F imou cameras don't work in HA

### ISSUE THREAD

**Issue by Whastie** [eavanvalkenburg/pysiaalarm#33]
IPC-A42-B and IPC-S42F imou cameras do not work in HA

After 6 months, I still can't get these two IMOU camera models to play video in HA.

has anyone been able to fix it? or can you help me

The model is: 4Mpx ranger 2 and 4mpx bullet cruiser.

Thanks a lot

**Comment by eavanvalkenburg** [comment]
Hi, the sia protocol has no support for cameras so this will never be fixed unfortunately...
